In [ ]:
# importing sentence transformer
from sentence_transformers import SentenceTransformer

In [ ]:
# import pandas for df operation
import pandas as pd
# import json for load .json file 
import json

In [ ]:
# importing torch for tensor operations
import torch

In [ ]:
# open appointments file in read
with open('../appointments_data.json', 'r') as f:
    # load json file into data
    data = json.load(f)

In [ ]:
# dowload pretrained qwen embeding with intialize embed mode
model = SentenceTransformer("Qwen/Qwen3-Embedding-0.6B")

Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`


In [ ]:
# get keys list using dict comprehession
keys = [ key for key in data.keys() ]

In [ ]:
# encode keys to get embedding
keys_embedding = model.encode(keys)

In [35]:
len(keys_embedding)

492

In [ ]:
# print embedding
for key_embed in keys_embedding:
    print(key_embed)

[ 0.02272247  0.03749488 -0.0141924  ... -0.02433016  0.00256265
 -0.01029206]
[-0.04450312  0.02892499 -0.00905474 ...  0.01381192  0.02612048
  0.01249637]
[ 0.01932932 -0.02087937 -0.01367982 ... -0.00346277 -0.00513759
 -0.00407159]
[ 0.00784208  0.03422493 -0.0110024  ... -0.02626081  0.00487803
 -0.0027201 ]
[ 0.00166302  0.02866468 -0.01420437 ... -0.02492237  0.03465147
 -0.00492068]
[-0.04621132  0.00872036 -0.01120309 ...  0.00774897  0.0202783
  0.0066942 ]
[-0.0248438   0.04308764 -0.01504096 ... -0.00853385 -0.01560559
  0.00820771]
[-0.05821269  0.01164905 -0.00934066 ...  0.00939335  0.01310597
  0.01551187]
[-0.03100682 -0.03078747 -0.01469999 ...  0.0088944  -0.01229251
  0.00785232]
[-0.02750762  0.02542803 -0.0135576  ... -0.00542389 -0.01245606
  0.01345445]
[-0.04305328  0.016642   -0.01558967 ... -0.01207412  0.00667312
  0.02005914]
[-0.06173343 -0.00245118 -0.01145421 ...  0.00681631  0.00621063
  0.01376848]
[ 0.02803598 -0.00502535 -0.01538568 ... -0.00958228 

In [ ]:
# query initialize
query = "Who is doctor of Brooke"

In [ ]:
# get embeding of query
query_embedding = model.encode(query)

In [53]:
query_embedding

array([ 0.05404025, -0.02819191, -0.01528522, ..., -0.02840265,
        0.03059081, -0.00247059], dtype=float32)

In [ ]:
# find similarity between query and keys
similarity = model.similarity(query_embedding, keys_embedding)

In [55]:
len(similarity[0])

492

In [56]:
similarity = torch.tensor(similarity)

C:\Users\BishwajyotiChaudhary\AppData\Local\Temp\ipykernel_20844\2568276563.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  similarity = torch.tensor(similarity)


In [ ]:
# topk gives top score and index
scores, top10_indices = torch.topk(similarity, k=10)

In [65]:
top10_indices

tensor([[192, 336,  48, 456, 174,  24, 240, 228, 408, 180]])

In [72]:
scores

tensor([[0.8624, 0.7784, 0.7756, 0.7756, 0.7686, 0.7684, 0.7676, 0.7660, 0.7651,
         0.7641]])

In [ ]:
# intialize dict keys 10 for top 10
keys_10 = {}
# use list comprehession to get top ten keys
top10_key =  [keys[i] for  i in top10_indices[0]]
# use list comprehession to get top ten score
top10_scores = [i for i in scores[0]]



In [81]:
top10_scores

[tensor(0.8624),
 tensor(0.7784),
 tensor(0.7756),
 tensor(0.7756),
 tensor(0.7686),
 tensor(0.7684),
 tensor(0.7676),
 tensor(0.7660),
 tensor(0.7651),
 tensor(0.7641)]

In [77]:
top10_key

['Brooke_doctor',
 'Derek_doctor',
 'Daniel_doctor',
 'Robert_doctor',
 'Brenda_doctor',
 'Laurie_doctor',
 'Nicholas_doctor',
 'Kenneth_doctor',
 'Michael_doctor',
 'Joshua_doctor']

In [ ]:
# here iterate upto len of top10 keys
for i in range(len(top10_key)):
    # update dict with key and value as key and score
    keys_10[top10_key[i]] = top10_scores[i]

In [83]:
keys_10

{'Brooke_doctor': tensor(0.8624),
 'Derek_doctor': tensor(0.7784),
 'Daniel_doctor': tensor(0.7756),
 'Robert_doctor': tensor(0.7756),
 'Brenda_doctor': tensor(0.7686),
 'Laurie_doctor': tensor(0.7684),
 'Nicholas_doctor': tensor(0.7676),
 'Kenneth_doctor': tensor(0.7660),
 'Michael_doctor': tensor(0.7651),
 'Joshua_doctor': tensor(0.7641)}

In [86]:
print(top_10)

{'Who is doctor of Brooke': {'Brooke_doctor': tensor(0.8624), 'Derek_doctor': tensor(0.7784), 'Daniel_doctor': tensor(0.7756), 'Robert_doctor': tensor(0.7756), 'Brenda_doctor': tensor(0.7686), 'Laurie_doctor': tensor(0.7684), 'Nicholas_doctor': tensor(0.7676), 'Kenneth_doctor': tensor(0.7660), 'Michael_doctor': tensor(0.7651), 'Joshua_doctor': tensor(0.7641)}}


In [87]:
top_10

{'Who is doctor of Brooke': {'Brooke_doctor': tensor(0.8624),
  'Derek_doctor': tensor(0.7784),
  'Daniel_doctor': tensor(0.7756),
  'Robert_doctor': tensor(0.7756),
  'Brenda_doctor': tensor(0.7686),
  'Laurie_doctor': tensor(0.7684),
  'Nicholas_doctor': tensor(0.7676),
  'Kenneth_doctor': tensor(0.7660),
  'Michael_doctor': tensor(0.7651),
  'Joshua_doctor': tensor(0.7641)}}

In [ ]:
# get values from data dict into list of values
values = [i for i in data.values()]
values

['Dr. Wilson',
 '2026-03-27',
 'Psychiatry',
 'City Hospital',
 '(557)935-7463x543',
 '16:25',
 'Dr. Wilson',
 '2025-10-11',
 'Orthopedics',
 'City Hospital',
 '+1-502-840-1548x530',
 '12:51',
 'Dr. Anderson',
 '2026-05-28',
 'Pediatrics',
 'Mountain View Hospital',
 '340.929.8569x91127',
 '01:55',
 'Dr. Smith',
 '2026-04-11',
 'Dentist',
 'City Hospital',
 '001-328-824-4066x8146',
 '18:01',
 'Dr. Smith',
 '2026-06-02',
 'Dentist',
 'Global Care Hospital',
 '553.594.2082',
 '15:47',
 'Dr. Johnson',
 '2026-01-25',
 'Orthopedics',
 'Mountain View Hospital',
 '(566)988-2922x161',
 '11:24',
 'Dr. Roshan',
 '2025-11-14',
 'Neurology',
 'Global Care Hospital',
 '889-255-8882',
 '02:08',
 'Dr. Thomas',
 '2025-10-30',
 'Neurology',
 'Sunshine Medical Center',
 '643.627.2489',
 '18:28',
 'Dr. Anderson',
 '2025-12-23',
 'Radiology',
 'Patan Hospital',
 '804-947-4659x96793',
 '23:52',
 'Dr. Smith',
 '2026-07-03',
 'Orthopedics',
 'Mountain View Hospital',
 '798-972-2018',
 '22:53',
 'Dr. Moore',


In [ ]:
# conversion into list
keys_embeddings = [embed for embed in keys_embedding]

In [ ]:
# intialize dict data_0 with keys, keys_embedings, values
data_0 = {"Keys":  keys , "Keys Embedding":keys_embeddings, "Values":values}

In [105]:
keys_embeddings

[array([ 0.02272247,  0.03749488, -0.0141924 , ..., -0.02433016,
         0.00256265, -0.01029206], dtype=float32),
 array([-0.04450312,  0.02892499, -0.00905474, ...,  0.01381192,
         0.02612048,  0.01249637], dtype=float32),
 array([ 0.01932932, -0.02087937, -0.01367982, ..., -0.00346277,
        -0.00513759, -0.00407159], dtype=float32),
 array([ 0.00784208,  0.03422493, -0.0110024 , ..., -0.02626081,
         0.00487803, -0.0027201 ], dtype=float32),
 array([ 0.00166302,  0.02866468, -0.01420437, ..., -0.02492237,
         0.03465147, -0.00492068], dtype=float32),
 array([-0.04621132,  0.00872036, -0.01120309, ...,  0.00774897,
         0.0202783 ,  0.0066942 ], dtype=float32),
 array([-0.0248438 ,  0.04308764, -0.01504096, ..., -0.00853385,
        -0.01560559,  0.00820771], dtype=float32),
 array([-0.05821269,  0.01164905, -0.00934066, ...,  0.00939335,
         0.01310597,  0.01551187], dtype=float32),
 array([-0.03100682, -0.03078747, -0.01469999, ...,  0.0088944 ,
       

In [ ]:
# create dataframe with columns keys, keys embeddings and vlaues
vector_data = pd.DataFrame(data=data_0)

In [108]:
vector_data

Keys  \
0                Lauren_doctor   
1      Lauren_appointment_date   
2    Lauren_checkup_department   
3     Lauren_hospital_location   
4               Lauren_contact   
..                         ...   
487      Gail_appointment_date   
488    Gail_checkup_department   
489     Gail_hospital_location   
490               Gail_contact   
491      Gail_appointment_time   

                                        Keys Embedding                  Values  
0    [0.022722473, 0.03749488, -0.014192398, 0.0456...              Dr. Wilson  
1    [-0.04450312, 0.028924987, -0.009054742, -0.04...              2026-03-27  
2    [0.019329315, -0.02087937, -0.013679822, -0.00...              Psychiatry  
3    [0.007842083, 0.034224935, -0.0110024, 0.02025...           City Hospital  
4    [0.0016630151, 0.028664678, -0.014204372, -0.0...       (557)935-7463x543  
..                                                 ...                     ...  
487  [-0.054638974, 0.015382473, -0.008915048, -0.0...              2025-12-08  
488  [-0.027756618, -0.035793655, -0.013047396, 0.0...               Radiology  
489  [-0.026429946, 0.019986693, -0.011967053, 0.01...  Mountain View Hospital  
490  [-0.032080475, 0.008330976, -0.013580643, -0.0...    +1-879-447-7114x0230  
491  [-0.059743665, -0.005647126, -0.01037159, -0.0...                   11:18  

[492 rows x 3 columns]

In [ ]:
# save data into csv file
vector_data.to_csv("Key_value_table.csv")